# -*- coding: UTF-8 -*-

news_domains_PT = [
    { "url":"http://publico.pt/", "name": "PUBLICO", "lang":"pt"},
	{ "url":"http://www.dn.pt/", "name": "Diario de Noticias", "lang":"pt"},
	{ "url":"http://dnoticias.pt/", "name": "DNoticias", "lang":"pt"},
	{ "url":"http://www.rtp.pt/", "name": "RTP", "lang":"pt"},
	{ "url":"http://www.cmjornal.pt/", "name": "Correio da Manha", "lang":"pt"},
	{ "url":"http://www.iol.pt/", "name": "IOL", "lang":"pt"},
	{ "url":"http://www.tvi24.iol.pt/", "name": "tvi24", "lang":"pt"},
	{ "url":"http://noticias.sapo.pt/", "name": "Noticias SAPO", "lang":"pt"},
	{ "url":"http://www.sapo.pt/", "name": "SAPO", "lang":"pt"},
	{ "url":"http://expresso.sapo.pt/", "name": "Expresso", "lang":"pt"},
	{ "url":"http://sol.sapo.pt/", "name": "SOL", "lang":"pt"},
	{ "url":"http://www.jornaldenegocios.pt/", "name": "Jornal de Negocios", "lang":"pt"},
	{ "url":"http://abola.pt/", "name": "A Bola", "lang":"pt"},
	{ "url":"http://www.jn.pt/", "name": "Jornal de Noticias", "lang":"pt"},
	{ "url":"http://sicnoticias.sapo.pt/", "name": "SIC Noticias", "lang":"pt"},
	{ "url":"http://www.lux.iol.pt/", "name": "Lux", "lang":"pt"},
	{ "url":"http://www.ionline.pt/", "name": "Jornal i", "lang":"pt"},
	{ "url":"http://news.google.pt/", "name": "Google Noticias", "lang":"pt"},
	{ "url":"http://www.dinheirovivo.pt/", "name": "Dinheiro Vivo", "lang":"pt"},
	{ "url":"http://www.aeiou.pt/", "name": "AEIOU", "lang":"pt"},
	{ "url":"http://www.tsf.pt/", "name": "TSF", "lang":"pt"},
	{ "url":"http://meiosepublicidade.pt/", "name": "Meios & Publicidade", "lang":"pt"},
	{ "url":"http://www.sabado.pt/", "name": "SABADO", "lang":"pt"},
	{ "url":"http://economico.sapo.pt/", "name": "Jornal Econômico", "lang":"pt"}
]

domain_blacklist = ['parlamento.pt',
                    'vidaeconomica.pt',
                    'jornalfiscal.pt',       
                    'tretas.org',
                    'issuu.com',
                    'dre.tretas.org',
                    'cm-lisboa.pt',
                    'netconsumo.com',
                    'assistente-tecnico.blogspot.pt',
                    'leisanotadas.advogados-carlajobling.pt',
                    'pcp.pt',
                    'es.scribd.com',
                    'eapnimprensa.blogspot.pt',
                    'briefing.pt',
                    'advogados-carlajobling.pt',
                    'osverdes.pt',
                    'eduprofs.blogspot.pt',
                    'jurindex3.advogados-carlajobling.pt',
                    'blocodeesquerdaindependente.blogspot.pt',
                    'agencia.ecclesia.pt',
                    'base.alra.pt:82',
                    'inclusaoaquilino.blogspot.pt',
                    'averdade.com',
                    'unmultimedia.org',
                    'vexataquaestio.blogspot.pt',]
